### ISSUE TITLE
增加应用图标

### ISSUE THREAD

**Issue by amokiel** [qiuxiang/genshin-maps#2]
感谢作者，体验确实优秀，丝滑流畅，功能也很全面。可以考虑增加一个应用图标，图标可以是这样的。
![原神地图_ICON](https://user-images.githubusercontent.com/70591216/225482679-a4f69fbb-8f61-40cc-9b85-334d2895ddb5.png)
应用的中文名也可以更改为原神地图，这样就很协调了。
再次感谢开发者，辛苦了。

**Comment by qiuxiang** [comment]
我会考虑加上去的，之后还会加上地下地图，地区切换

**Comment by qiuxiang** [comment]
也可以考虑，主要是要写自动发布的脚本
