### ISSUE TITLE
提高地图清晰度

### ISSUE THREAD

**Issue by amokiel** [qiuxiang/genshin-maps#4]
我平时用平板电脑看地图，发现放大之后清晰度似乎有点不太好，有明显锯齿。是否有可能提高一些地图的清晰度，或者可以做成设置可选显示模式。辛苦了，多谢！

**Comment by qiuxiang** [comment]
现在的地图是米游社的，清晰度确实不太行

**Comment by qiuxiang** [comment]
数据和地图是关联的，换地图很麻烦，不打算再改了，要是介意清晰度就换这个用 https://github.com/kongying-tavern/flutter-genshin-map
