### ISSUE TITLE
添加标记功能(收集完成标记也行)，备份功能

### ISSUE THREAD

**Issue by Memory2314** [qiuxiang/genshin-maps#5]

**Comment by Memory2314** [comment]
这个一个很不错的项目，在运行很流程，而且每个神瞳收集都有gif动图，备份功能可以使用第三方工具，不过没有标记真的很难受😣

**Comment by qiuxiang** [comment]
我自己是不用标记功能，不过我也有想过怎么简单实现。

对了，你是用什么哪个平台的客户端？web？android？

**Comment by Memory2314** [comment]
> 我自己是不用标记功能，不过我也有想过怎么简单实现。
> 
> 对了，你是用什么哪个平台的客户端？web？android？

Android

**Comment by qiuxiang** [comment]
考虑下个版本实现

**Comment by qiuxiang** [comment]
已添加
